- name: Deploy DockerHub app to Kubernetes
  hosts: launched
  become: yes
  tasks:
    - name: Create Deployment
      copy:
        dest: /tmp/app-deployment.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: sample-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: sample-app
            template:
              metadata:
                labels:
                  app: sample-app
              spec:
                containers:
                - name: sample-app
                  image: hassanhbahmed/sample-app:{{ image_tag }}
                  ports:
                  - containerPort: 80

    - name: Apply Deployment
      shell: kubectl apply -f /tmp/app-deployment.yaml --kubeconfig=/home/ec2-user/.kube/config

    - name: Create NodePort Service with specific port
      copy:
        dest: /tmp/sample-app-service.yaml
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: sample-app
          spec:
            type: NodePort
            selector:
              app: sample-app
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
                nodePort: 32029

    - name: Apply Service
      shell: kubectl apply -f /tmp/sample-app-service.yaml --kubeconfig=/home/ec2-user/.kube/config
